package com.alura.jdbc.pruebas;

import com.alura.jdbc.com.alura.jdbc.fantory.ConnectionFactory;

import java.sql.Connection;
import java.sql.SQLException;

public class PruebaConexion {

    public static void main(String[] args) throws SQLException {
        Connection con = new ConnectionFactory().recuperaConexion();

        System.out.println("Cerrando la conexi√≥n");

        con.close();
    }

}
